package io.jpress.module.form.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.form.model.base.BaseFormInfo;

import java.util.HashMap;

/**
 * Generated by JPress.
 */
@Table(tableName = "form_info", primaryKey = "id")
public class FormInfo extends BaseFormInfo<FormInfo> {

    private static final long serialVersionUID = 1L;
    private static HashMap<Integer,String> map = new HashMap();
    public static final String STATUS_NORMAL = "0";  //未处理的
    public static final String STATUS_PROCESSED = "1";  //已处理的
    public static final String STATUS_TRASH = "2";   //废弃的
    public static final String COLUMN_TYPE_NAME = "name";   //名字
    public static final String COLUMN_TYPE_MOBILE = "mibile";   //电话
    public static final String COLUMN_TYPE_ADDRESS = "address";   //地址
    public static final String COLUMN_TYPE_DESC = "desc";   //描述


    public FormInfo() {
        map.put(0,"选择房型");
        map.put(1,"一室一厅");
        map.put(2,"两室两厅");
        map.put(3,"三室一厅");
        map.put(4,"三室两厅");
        map.put(5,"四室两厅");
        map.put(6,"四室三厅");
        map.put(7,"五室两厅");
        map.put(8,"五室三厅");
        map.put(9,"别墅");
        map.put(10,"大平层");
        map.put(11,"大厦/小区/商超");
        map.put(12,"酒店/宾馆");
        map.put(13,"其他");
    }

    public String getHouseTypeDesc() {
        return map.get(getHousetype());
    }
}
