package io.jpress.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContact<M extends BaseContact<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 姓名
     */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 姓名
     */
	public java.lang.String getName() {
		return getStr("name");
	}

    /**
     * 电话
     */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

    /**
     * 电话
     */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

    /**
     * 城市
     */
	public void setCity(java.lang.String city) {
		set("city", city);
	}

    /**
     * 城市
     */
	public java.lang.String getCity() {
		return getStr("city");
	}

    /**
     * 区域
     */
	public void setArea(java.lang.String area) {
		set("area", area);
	}

    /**
     * 区域
     */
	public java.lang.String getArea() {
		return getStr("area");
	}

    /**
     * 服务
     */
	public void setService(java.lang.String service) {
		set("service", service);
	}

    /**
     * 服务
     */
	public java.lang.String getService() {
		return getStr("service");
	}

	/**
	 * 创建日期
	 */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	/**
	 * 创建日期
	 */
	public java.util.Date getCreated() {
		return get("created");
	}

    /**
     * 表单状态：0、未处理 1、已查看 2、已废弃
     */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 表单状态：0、未处理 1、已查看 2、已废弃
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
