package io.jpress.module.example.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExampleImage<M extends BaseExampleImage<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setExampleId(java.lang.Long exampleId) {
		set("example_id", exampleId);
	}

	public java.lang.Long getExampleId() {
		return getLong("example_id");
	}

	public void setSrc(java.lang.String src) {
		set("src", src);
	}

	public java.lang.String getSrc() {
		return getStr("src");
	}

	public void setOrderNumber(java.lang.Integer orderNumber) {
		set("order_number", orderNumber);
	}

	public java.lang.Integer getOrderNumber() {
		return getInt("order_number");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return getDate("created");
	}

}
