package io.jpress.module.contact.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.contact.model.base.BaseContact;

/**
 * Generated by JPress.
 */
@Table(tableName = "contact", primaryKey = "id")
public class Contact extends BaseContact<Contact> {

    private static final long serialVersionUID = 1L;

	
}
