package io.jpress.module.page.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePageContact<M extends BasePageContact<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 名字
     */
	public void setName(String name) {
		set("name", name);
	}

    /**
     * 名字
     */
	public String getName() {
		return getStr("getString");
	}

    /**
     * 评论的作者
     */
	public void setMobile(String mobile) {
		set("mobile", mobile);
	}

    /**
     * 评论的作者
     */
	public String getMobile() {
		return getStr("mobile");
	}

    /**
     * 邮箱
     */
	public void setCity(String city) {
		set("city", city);
	}

    /**
     * 邮箱
     */
	public String getCity() {
		return getStr("city");
	}

    /**
     * 微信号
     */
	public void setArea(String area) {
		set("area", area);
	}

    /**
     * 微信号
     */
	public String getArea() {
		return getStr("area");
	}

	/**
	 * 微信号
	 */
	public void setService(String service) {
		set("service", service);
	}

	/**
	 * 微信号
	 */
	public String getService() {
		return getStr("service");
	}


}
