package io.jpress.module.example.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.example.model.base.BaseExampleImage;

/**
 * Generated by JPress.
 */
@Table(tableName = "example_image", primaryKey = "id")
public class ExampleImage extends BaseExampleImage<ExampleImage> {

    private static final long serialVersionUID = 1L;

	
}
