package io.jpress.model;

import io.jboot.db.annotation.Table;
import io.jpress.commons.pay.ContactStatus;
import io.jpress.model.base.BaseContact;

/**
 * Generated by JPress.
 */
@Table(tableName = "contact", primaryKey = "id")
public class Contact extends BaseContact<Contact> {

    private static final long serialVersionUID = 1L;

    public boolean isContactUnDeal() {
        ContactStatus contactStatus = ContactStatus.getByStatus(getStatus());

        return contactStatus != null && contactStatus == ContactStatus.UNDEAL;
    }

    public String getStatusText(){
           return ContactStatus.getTextByInt(getStatus());
    }
}
