package io.jpress.module.page.model;

import io.jboot.db.annotation.Table;
import io.jpress.commons.utils.CommonsUtils;
import io.jpress.commons.utils.JsoupUtils;
import io.jpress.model.User;
import io.jpress.module.page.model.base.BasePageContact;
import io.jpress.module.page.model.base.BaseSinglePageComment;

import java.util.HashMap;
import java.util.Map;

/**
 * Generated by JPress.
 */
@Table(tableName = "contact", primaryKey = "id")
public class PageContact extends BasePageContact<PageContact> {
    public static final String STATUS_NORMAL = "normal"; //正常
    public static final String STATUS_UNAUDITED = "unaudited"; //待审核
    public static final String STATUS_TRASH = "trash"; //垃圾箱

    private static final long serialVersionUID = 1L;
	
}
