package io.jpress.module.form.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFormInfo<M extends BaseFormInfo<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 姓名
     */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 姓名
     */
	public java.lang.String getName() {
		return getStr("name");
	}

    /**
     * 电话
     */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

    /**
     * 电话
     */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

    /**
     * 详细地址
     */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}

    /**
     * 详细地址
     */
	public java.lang.String getAddress() {
		return getStr("address");
	}

    /**
     * 面积
     */
	public void setArea(java.lang.Integer area) {
		set("area", area);
	}

    /**
     * 面积
     */
	public java.lang.Integer getArea() {
		return getInt("area");
	}

    /**
     * 房型
     */
	public void setHousetype(java.lang.Integer housetype) {
		set("housetype", housetype);
	}

    /**
     * 房型
     */
	public java.lang.Integer getHousetype() {
		return getInt("housetype");
	}

    /**
     * 额外的需求描述
     */
	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

    /**
     * 额外的需求描述
     */
	public java.lang.String getDesc() {
		return getStr("desc");
	}

    /**
     * 提交的时间
     */
	public void setTime(java.util.Date time) {
		set("time", time);
	}

    /**
     * 提交的时间
     */
	public java.util.Date getTime() {
		return get("time");
	}

}
